export const tax_structure = [
  {
    province: 'Alberta',
    label: 'GST 5%',
    gst: 5,
    pst: 0,
    hst: 0,
    total: 5,
  },
  {
    province: 'British Columbia',
    label: 'GST 5%, PST 7%',
    gst: 5,
    pst: 7,
    hst: 0,
    total: 12,
  },
  {
    province: 'Manitoba',
    label: 'GST 5%, PST 7%',
    gst: 5,
    pst: 7,
    hst: 0,
    total: 12,
  },
  {
    province: 'New Brunswick',
    label: 'GST 5%, HST 15%',
    gst: 5,
    pst: 0,
    hst: 15,
    total: 20,
  },
  {
    province: 'Newfoundland and Labrador',
    label: 'GST 5%, HST 15%',
    gst: 5,
    pst: 0,
    hst: 15,
    total: 20,
  },
  {
    province: 'Northwest Territories',
    label: 'GST 5%',
    gst: 5,
    pst: 0,
    hst: 0,
    total: 5,
  },
  {
    province: 'Nova Scotia',
    label: 'GST 5%, HST 15%',
    gst: 5,
    pst: 0,
    hst: 15,
    total: 20,
  },
  {
    province: 'Nunavut',
    label: 'GST 5%',
    gst: 5,
    pst: 0,
    hst: 0,
    total: 5,
  },
  {
    province: 'Ontario',
    label: 'GST 5%, HST 13%',
    gst: 5,
    pst: 0,
    hst: 13,
    total: 18,
  },
  {
    province: 'Prince Edward Island',
    label: 'GST 5%, HST 15%',
    gst: 5,
    pst: 0,
    hst: 15,
    total: 20,
  },
  {
    province: 'Quebec',
    label: 'GST 5%, PST 9.975%',
    gst: 5,
    pst: 9.975,
    hst: 0,
    total: 14.975,
  },
  {
    province: 'Saskatchewan',
    label: 'GST 5%, PST 6%',
    gst: 5,
    pst: 6,
    hst: 0,
    total: 11,
  },
  {
    province: 'Yukon',
    label: 'GST 5%',
    gst: 5,
    pst: 0,
    hst: 0,
    total: 5,
  },
];
